[tool.poetry]
name = "jup"
version = "0.1.0"
description = ""
authors = ["gaohaoye <gaohaoye@inke.cn>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
matplotlib = "^3.7.1"
ipykernel = "^6.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
